using System.Linq;
using UnityEngine;
using UnityEditorInternal;

namespace UnityCodeGen.Samples.TagsAndLayers
{
    [Generator]
    public class LayersGenerator : ICodeGenerator
    {
        public void Execute(GeneratorContext context)
        {
            var tags = InternalEditorUtility.layers
                .Select(x => $"public const int {x.Replace(" ", string.Empty)} = {LayerMask.NameToLayer(x)};");
            var fields = string.Join("\n\t", tags);
            var code =
@$"//<auto-generated/>
public static class Layers
{{
    {fields}
}}";
            context.AddCode("Tags & Layers/Layers.Generated.cs", code);
        }
    }
}