using System.Linq;
using System.Collections.Generic;
using UnityEngine;
using UnityEditor;
using UnityEditorInternal;

namespace UnityCodeGen.Samples.TagsAndLayers
{
    [Generator]
    public class SortingLayersGenerator : ICodeGenerator
    {
        public void Execute(GeneratorContext context)
        {
            var tagManager = new SerializedObject(AssetDatabase.LoadAllAssetsAtPath("ProjectSettings/TagManager.asset")[0]);
            var sortingLayer = tagManager.FindProperty("m_SortingLayers");
            var list = new List<string>();
            for (int i = 0; i < sortingLayer.arraySize; ++i)
            {
                list.Add(sortingLayer.GetArrayElementAtIndex(i).displayName);
            }
            var layers = list
                .Select(x => $"public const string {x.Replace(" ", string.Empty)} = \"{x}\";");
            var fields = string.Join("\n\t", layers);
            var code =
@$"//<auto-generated/>
public static class SortingLayers
{{
    {fields}
}}";
            context.AddCode("Tags & Layers/SortingLayers.Generated.cs", code);
        }
    }
}